server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql

  mail:
    protocol: smtp
    test-connection: true
    port: 1025
    host: localhost
    username: username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            required: true
            enable: true
          connectiontimeout: 5000
          timeout: 3000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html


urlShortener:
  baseUrl: "http://localhost:8080/api/v1/url-shortener/"
  scheduledJobDelay: "PT5M"
  schedulerJobInitialDelay : "PT5M"

  mail:
    fromAddress: "urlshortener@buyukkaya.com"
    templatePath: "/templates/email/CompletionMailTemplate.html"


